import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <script src="/js/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/jquery.magnific.min.js"></script>
        <script src="/js/swiper-bundle.min.js"></script>
        <script src="/js/counter.js"></script>
        <script src="/js/progressbar.js"></script>
        <script src="/js/gsap.min.js"></script>
        <script src="/js/scrollSmoother.js"></script>
        <script src="/js/scrollToPlugin.min.js"></script>
        <script src="/js/sccrollTrigger.js"></script>
        <script src="/js/SplitText.min.js"></script>
        <script src="/js/jquery.meanmenu.min.js"></script>
        <script src="/js/backToTop.js"></script>
        <script src="/js/main.js"></script>
        <script src="/js/errorHandling.js"></script>
        <script src="/js/offCanvas.js"></script>
      </body>
    </html>
  );
}
